# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radius}
  s.version = "0.7.0.prerelease"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{John W. Long (me@johnwlong.com)}, %q{David Chelimsky (dchelimsky@gmail.com)}, %q{Bryce Kerley (bkerley@brycekerley.net)}]
  s.date = %q{2011-06-13}
  s.description = %q{Radius is a powerful tag-based template language for Ruby inspired by the template languages used in MovableType and TextPattern. It uses tags similar to XML, but can be used to generate any form of plain text (HTML, e-mail, etc...).}
  s.email = %q{me@johnwlong.com}
  s.extra_rdoc_files = [
    "CHANGELOG",
    "LICENSE",
    "QUICKSTART.rdoc",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "QUICKSTART.rdoc",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/radius.rb",
    "lib/radius/context.rb",
    "lib/radius/delegating_open_struct.rb",
    "lib/radius/error.rb",
    "lib/radius/ord_string.rb",
    "lib/radius/parse_tag.rb",
    "lib/radius/parser.rb",
    "lib/radius/parser/JavaScanner$Flavor.class",
    "lib/radius/parser/JavaScanner$Tag.class",
    "lib/radius/parser/JavaScanner.class",
    "lib/radius/parser/JavaScanner.java",
    "lib/radius/parser/JavaScanner.rl",
    "lib/radius/parser/java_scanner.jar",
    "lib/radius/parser/scanner.rb",
    "lib/radius/parser/scanner.rl",
    "lib/radius/parser/squiggle_scanner.rb",
    "lib/radius/parser/squiggle_scanner.rl",
    "lib/radius/tag_binding.rb",
    "lib/radius/tag_definitions.rb",
    "lib/radius/utility.rb",
    "lib/radius/version.rb",
    "tasks/jeweler.rake",
    "tasks/rdoc.rake",
    "tasks/rubinius.rake",
    "tasks/scan.rake",
    "tasks/test.rake",
    "test/benchmarks.rb",
    "test/context_test.rb",
    "test/multithreaded_test.rb",
    "test/ord_string_test.rb",
    "test/parser_test.rb",
    "test/quickstart_test.rb",
    "test/squiggle_test.rb",
    "test/test_helper.rb",
    "test/utility_test.rb"
  ]
  s.homepage = %q{http://github.com/jlong/radius}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{A tag-based templating language for Ruby.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<RedCloth>, [">= 0"])
    else
      s.add_dependency(%q<RedCloth>, [">= 0"])
    end
  else
    s.add_dependency(%q<RedCloth>, [">= 0"])
  end
end

